plugins {
    id("org.springframework.boot") version "4.0.1" apply false
    id("io.spring.dependency-management") version "1.1.7" apply false
    id("java")
    id("com.google.protobuf") version "0.9.5" apply false
}

group = "com.hotelio"
version = "1.0.0"

ext {
    set("springGrpcVersion", "1.0.0")
}

repositories {
    mavenCentral()
}


